### ISSUE TITLE
Linux Build: Segmentation Error ( Core Dumped )

### ISSUE THREAD

**Issue by ArthurRichard** [undefined-darkness/open-horizon#1]
On Ubuntu 14.04,
The build is working. While we launch the program without datafile.qdf, the error message is appearing:  _unable to open archive datafile.qdf_
                    _unable to open datafile.qdf_
at least some parts of the build are working. But when we put the datafile.qdf in the same folder, there is a little delay at the launch and then:
                     _Segmentation error (core dumped)_
Here is the gdb output: 
*Starting program: /home/arthrik/open-horizon-cmake/open_horizon 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__GI_fseek (fp=0x41, offset=1473731952, whence=0) at fseek.c:38
38  fseek.c: No such file or directory.*

I hope it's not due to lack of resources from my machine, but with this, it should normally work:
Memory: 3.9 Gio
CPU: Intel® Core™2 Duo CPU E4600 @ 2.40GHz × 2 
GPU: GeForce GTS 250/PCIe/SSE2
OS Type: 32 bits

**Comment by undefined-darkness** [comment]
fixed
