### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by ghost** [undefined-darkness/open-horizon#2]
1. I have followed the [build instructions](https://github.com/undefined-darkness/open-horizon/wiki/Build-instructions)
2. On run I get [this warning](https://cloud.githubusercontent.com/assets/1475489/18808517/3fc1c1a6-826d-11e6-846b-b27c7237b60c.jpg) then I have no idea which folder to select
3. After selecting any folder I get [these errors](https://cloud.githubusercontent.com/assets/1475489/18808518/3fc42388-826d-11e6-891f-1f78411bffdb.jpg).

OS: Ubuntu 16.04

**Comment by undefined-darkness** [comment]
This game requires proprietary resources. Please specify path to installed Assault Horizon, not the Open Horizon's path. 

By the way, Assault Horizon is currently on sale on Humble Store.

**Comment by ghost** [comment]
Thanks. I will try to buy [it](https://www.humblebundle.com/store/ace-combat-assault-horizon-enhanced-edition) later
