### ISSUE TITLE
"Wanderer" AI state?

### ISSUE THREAD

**Issue by Chelsea486MHz** [undefined-darkness/open-horizon#3]
From the `game/ai.h` header:

enum state
    {
        state_wander,
        state_approach,
        state_pursuit,
        state_follow,
};

This enumeration is part of the `ai` class, as I can see. I didn't really look into it, but from my understanding the first state (`state_wander`) doesn't look like anything I've encountered in the original games.

From my understanding, this state defines the AI's behaviour.

Do you think this state is useful? If so, what is it doing exactly? What do you intend to use it for? Do you think that, if I am right and AI shouldn't roam aimlessly, there could be a more efficient way to implement a "standby" state?

**Comment by undefined-darkness** [comment]
This ai is for player-like planes in multiplayer modes. This state makes bot fly in wide circles until he spot some targets. I actually wrote this class as a placeholder, but it works surprisingly well. What you are looking for is unit_vehicle, particularly update function.
